### ISSUE TITLE
Polling is broken(potential triggers without reason) in Pipeline using SCM in job and SCM step in Pipeline script

### ISSUE THREAD

**Issue by bicschneider** [Praqma/pretested-integration-plugin#128]
Using setup from #126 

```
 > git.exe log --full-history --no-abbrev --format=raw -M -m a7894f5716f0ed5058e8cead39c9297b7c32742c..aba8779de758e930c475b7a4f5a7e0f134d973a7 # timeout=10
ERROR: Failed to determine if we want to exclude aba8779de758e930c475b7a4f5a7e0f134d973a7
hudson.plugins.git.GitException: Command "git.exe log --full-history --no-abbrev --format=raw -M -m a7894f5716f0ed5058e8cead39c9297b7c32742c..aba8779de758e930c475b7a4f5a7e0f134d973a7" returned status code 128:
stdout: 
stderr: fatal: Invalid revision range a7894f5716f0ed5058e8cead39c9297b7c32742c..aba8779de758e930c475b7a4f5a7e0f134d973a7

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1924)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1892)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1888)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1533)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.showRevision(CliGitAPIImpl.java:934)
	at hudson.plugins.git.GitSCM.isRevExcluded(GitSCM.java:1764)
	at hudson.plugins.git.GitSCM.compareRemoteRevisionWithImpl(GitSCM.java:717)
	at hudson.plugins.git.GitSCM.compareRemoteRevisionWith(GitSCM.java:592)
	at org.jenkinsci.plugins.workflow.job.WorkflowJob.poll(WorkflowJob.java:618)
	at hudson.triggers.SCMTrigger$Runner.runPolling(SCMTrigger.java:528)
	at hudson.triggers.SCMTrigger$Runner.run(SCMTrigger.java:574)
	at hudson.util.SequentialExecutionQueue$QueueEntry.run(SequentialExecutionQueue.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Done. Took 7,1 sec
Changes found
```

**Comment by sofusalbertsen** [comment]
Have had the same error. Is it fixed with the commit @bicschneider ?
