### ISSUE TITLE
Research broken integration tests for pipeline compliancy

### ISSUE THREAD

**Issue by groenborg** [Praqma/pretested-integration-plugin#68]
The integration tests are failing all at once, and we need to investigate which commit introduces changes that breaks the system

**Comment by buep** [comment]
Work on my machine:

```
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 26.931 sec - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.UseAuthorOfLastCommitIT

Results :

Tests run: 73, Failures: 0, Errors: 0, Skipped: 7

[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] 
[INFO] --- maven-failsafe-plugin:2.17:verify (default) @ pretested-integration ---
[INFO] Failsafe report directory: /home/bue/github-repos/praqma/pretested-integration-plugin/target/failsafe-reports
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ pretested-integration ---
[INFO] Installing /home/bue/github-repos/praqma/pretested-integration-plugin/target/pretested-integration.hpi to /home/bue/.m2/repository/org/jenkins-ci/plugins/pretested-integration/2.4.1/pretested-integration-2.4.1.hpi
[INFO] Installing /home/bue/github-repos/praqma/pretested-integration-plugin/pom.xml to /home/bue/.m2/repository/org/jenkins-ci/plugins/pretested-integration/2.4.1/pretested-integration-2.4.1.pom
[INFO] Installing /home/bue/github-repos/praqma/pretested-integration-plugin/target/pretested-integration.jar to /home/bue/.m2/repository/org/jenkins-ci/plugins/pretested-integration/2.4.1/pretested-integration-2.4.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17:19 min
[INFO] Finished at: 2017-09-19T12:27:34+02:00
[INFO] Final Memory: 58M/609M
[INFO] ------------------------------------------------------------------------
bue@orange-two:~/github-repos/praqma/pretested-integration-plugin$ 
bue@orange-two:~/github-repos/praqma/pretested-integration-plugin$ 
bue@orange-two:~/github-repos/praqma/pretested-integration-plugin$ 
bue@orange-two:~/github-repos/praqma/pretested-integration-plugin$ git log -n1
commit 409ae1fb573777779eac155f96f57358e12f4068
Author: ReleasePraqma <release@praqma.net>
Date:   Thu Jun 9 09:56:43 2016 +0200

    [maven-release-plugin] prepare release pretested-integration-2.4.1
bue@orange-two:~/github-repos/praqma/pretested-integration-plugin$ git status
HEAD detached at pretested-integration-2.4.1
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	deleted:    .hgignore
	deleted:    .hgtags

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   README.md

bue@orange-two:~/github-repos/praqma/pretested-integration-plugin$ 
```

```
bue@orange-two:~/github-repos/praqma/pretested-integration-plugin$ mvn -version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /usr/local/apache-maven-3.5.0
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.10.0-35-generic", arch: "amd64", family: "unix"
bue@orange-two:~/github-repos/praqma/pretested-integration-plugin$
```

**Comment by buep** [comment]
I ran it again still successfull

**Comment by groenborg** [comment]
Working commits: 
- `bf27d83`

**Comment by buep** [comment]
Working commits:

* pretested-integration-2.4.1

**Comment by groenborg** [comment]
### FAIL 1

Results :

Tests in error: 
  FailedTest.org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite » IllegalArgument

Tests run: 8, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23.304 s
[INFO] Finished at: 2017-09-19T13:32:27+02:00
[INFO] Final Memory: 57M/998M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project pretested-integration: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/simon/Github/praqma/pretested-integration-plugin/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by buep** [comment]
I see failures on this commit: `f1f33822b878c93f3748d3d4f0915422855b32a5`

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT
Tests run: 9, Failures: 1, Errors: 8, Skipped: 0, Time elapsed: 210.449 sec <<< FAILURE! - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT
checkMultiScmWithTwoGitonfigurationAmbiguousName(org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT)  Time elapsed: 22.144 sec  <<< FAILURE!
junit.framework.AssertionFailedError
	at org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT.checkMultiScmWithTwoGitonfigurationAmbiguousName(JENKINS_24754_IT.java:388)

successWithMatchingRepositoryNames(org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT)  Time elapsed: 181.412 sec  <<< ERROR!
java.lang.InterruptedException
	at org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT.successWithMatchingRepositoryNames(JENKINS_24754_IT.java:256)

succesWithDefaultConfiguration2RepositoriesWithoutNames(org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT)  Time elapsed: 0.631 sec  <<< ERROR!
java.lang.IllegalStateException: Repository already exists: repo1.git
	at org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT.succesWithDefaultConfiguration2RepositoriesWithoutNames(JENKINS_24754_IT.java:63)

failImproperlyConfiguredMultiSCMTwoSeperateGitRepos(org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT)  Time elapsed: 1.231 sec  <<< ERROR!
java.lang.IllegalStateException: Repository already exists: test-repo2.git
	at org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT.failImproperlyConfiguredMultiSCMTwoSeperateGitRepos(JENKINS_24754_IT.java:491)

succesWithDefaultConfiguration2RepositoriesWithNameMatchDefaultConfig(org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT)  Time elapsed: 1.156 sec  <<< ERROR!
java.lang.IllegalStateException: Repository already exists: repo1.git
	at org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT.succesWithDefaultConfiguration2RepositoriesWithNameMatchDefaultConfig(JENKINS_24754_IT.java:162)

succesWithDefaultConfiguration2RepositoriesWithName(org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT)  Time elapsed: 0.733 sec  <<< ERROR!
java.lang.IllegalStateException: Repository already exists: repo1.git
	at org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT.succesWithDefaultConfiguration2RepositoriesWithName(JENKINS_24754_IT.java:108)

successWithDefaultConfiguration(org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT)  Time elapsed: 0.813 sec  <<< ERROR!
java.lang.IllegalStateException: Repository already exists: repo1.git
	at org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT.successWithDefaultConfiguration(JENKINS_24754_IT.java:294)

checkMultiScmWithTwoGitConfigurationAmbiguousName2(org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT)  Time elapsed: 0.757 sec  <<< ERROR!
java.lang.IllegalStateException: Repository already exists: test-repo1_1.git
	at org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT.checkMultiScmWithTwoGitConfigurationAmbiguousName2(JENKINS_24754_IT.java:417)

nothingToDo2RepositoriesWithNoMatchingName(org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT)  Time elapsed: 0.901 sec  <<< ERROR!
java.lang.IllegalStateException: Repository already exists: repo1.git
	at org.jenkinsci.plugins.pretestedintegration.integration.scm.git.JENKINS_24754_IT.nothingToDo2RepositoriesWithNoMatchingName(JENKINS_24754_IT.java:210)

Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.CustomIntegrationBranchIT
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 361.5 sec <<< FAILURE! - in org.jenkinsci.plugins.pretestedintegration.integration.scm.git.CustomIntegrationBranchIT
customIntegrationBranchSquashStrategy(org.jenkinsci.plugins.pretestedintegration.integration.scm.git.CustomIntegrationBranchIT)  Time elapsed: 180.674 sec  <<< ERROR!
java.lang.InterruptedException
	at org.jenkinsci.plugins.pretestedintegration.integration.scm.git.CustomIntegrationBranchIT.customIntegrationBranchSquashStrategy(CustomIntegrationBranchIT.java:56)

customIntegrationBranchAccumulatedStrategy(org.jenkinsci.plugins.pretestedintegration.integration.scm.git.CustomIntegrationBranchIT)  Time elapsed: 180.825 sec  <<< ERROR!
java.lang.InterruptedException
	at org.jenkinsci.plugins.pretestedintegration.integration.scm.git.CustomIntegrationBranchIT.customIntegrationBranchAccumulatedStrategy(CustomIntegrationBranchIT.java:169)

Running org.jenkinsci.plugins.pretestedintegration.integration.scm.git.FastForwardSingleCommitsIT
^Cbue@orange-two:~/github-repos/praqma/pretested-integration-plugin$ git status
HEAD detached at f1f3382
```

I'll diff back to latest release tag to see difference

**Comment by buep** [comment]
For me this diff introduces the problem: https://github.com/Praqma/pretested-integration-plugin/compare/pretested-integration-2.4.1...f1f33822b878c93f3748d3d4f0915422855b32a5

Only interesting thing there is the dependencies.

**Comment by buep** [comment]
So it is a dependency problem: 

```
Results :

Tests run: 73, Failures: 0, Errors: 0, Skipped: 7

[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] 
[INFO] --- maven-failsafe-plugin:2.17:verify (default) @ pretested-integration ---
[INFO] Failsafe report directory: /home/bue/github-repos/praqma/pretested-integration-plugin/target/failsafe-reports
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ pretested-integration ---
[INFO] Installing /home/bue/github-repos/praqma/pretested-integration-plugin/target/pretested-integration.hpi to /home/bue/.m2/repository/org/jenkins-ci/plugins/pretested-integration/2.4.2-SNAPSHOT/pretested-integration-2.4.2-SNAPSHOT.hpi
[INFO] Installing /home/bue/github-repos/praqma/pretested-integration-plugin/pom.xml to /home/bue/.m2/repository/org/jenkins-ci/plugins/pretested-integration/2.4.2-SNAPSHOT/pretested-integration-2.4.2-SNAPSHOT.pom
[INFO] Installing /home/bue/github-repos/praqma/pretested-integration-plugin/target/pretested-integration.jar to /home/bue/.m2/repository/org/jenkins-ci/plugins/pretested-integration/2.4.2-SNAPSHOT/pretested-integration-2.4.2-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16:11 min
[INFO] Finished at: 2017-09-19T14:48:29+02:00
[INFO] Final Memory: 59M/640M
[INFO] ------------------------------------------------------------------------
bue@orange-two:~/github-repos/praqma/pretested-integration-plugin$ git status
HEAD detached at f1f3382
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   pom.xml

no changes added to commit (use "git add" and/or "git commit -a")
bue@orange-two:~/github-repos/praqma/pretested-integration-plugin$ git diff
diff --git i/pom.xml w/pom.xml
index a0b05b7..b42c613 100644
--- i/pom.xml
+++ w/pom.xml
@@ -3,7 +3,7 @@
     <parent>
         <groupId>org.jenkins-ci.plugins</groupId>
         <artifactId>plugin</artifactId>
-        <version>1.625.3</version>
+        <version>1.580</version>
     </parent>
 
     <url>http://wiki.jenkins-ci.org/display/JENKINS/Pretested+Integration+Plugin</url>
@@ -121,6 +121,7 @@
             <plugin>
                 <groupId>org.jenkins-ci.tools</groupId>
                 <artifactId>maven-hpi-plugin</artifactId>
+                <version>1.115</version>
                 <configuration>
                     <pluginVersionDescription>${buildNumber}</pluginVersionDescription>
                     <compatibleSinceVersion>2.0</compatibleSinceVersion>
@@ -138,8 +139,8 @@
                 <groupId>org.apache.maven.plugins</groupId>
                 <artifactId>maven-compiler-plugin</artifactId>
                 <configuration>
-                    <source>1.8</source>
-                    <target>1.8</target>
+                    <source>1.7</source>
+                    <target>1.7</target>
                 </configuration>
             </plugin>
 
@@ -151,7 +152,7 @@
             <plugin>
                 <groupId>org.apache.maven.plugins</groupId>
                 <artifactId>maven-failsafe-plugin</artifactId>
-                <version>2.19.1</version>
+                <version>2.17</version>
                 <executions>
                     <execution>
                         <goals>
@@ -170,7 +171,7 @@
             <plugin>
                 <groupId>org.apache.maven.plugins</groupId>
                 <artifactId>maven-surefire-plugin</artifactId>
-                <version>2.19.1</version>
+                <version>2.17</version>
                 <configuration>
                     <excludes>
                         <exclude>**/CredentialsTest.java</exclude>
@@ -438,7 +439,7 @@
         <dependency>
             <groupId>org.jenkins-ci.plugins</groupId>
             <artifactId>git-client</artifactId>
-            <version>2.2.1</version>
+            <version>1.19.1</version>
         </dependency>
 
         <dependency>
bue@orange-two:~/github-repos/praqma/pretested-integration-plugin$ 
```

**Comment by buep** [comment]
Please continue in issue #70
